Mehrfache Dateien für Positiv- und Negativtest

diff --git a/create_railroad_keywords_from_pdf b/create_railroad_keywords_from_pdf
--- a/create_railroad_keywords_from_pdf
+++ b/create_railroad_keywords_from_pdf
@@ -52,36 +52,41 @@ function runTest () {
   pattern_name=$(basename "$pattern_case")
 
   # positive tests
-  test_name_positive=${pattern_name//pattern/positive.list}
-  test_case_positive="$test_path/$test_name_positive"
-  test_results=$(getResults "$pattern_case" "$test_case_positive")
-  matched_elements=$(echo "$test_results" | sed '/^$/d' | wc -l)
-  given_elements=$(sed '/^pattern=/d' "$test_case_positive" | sed '/^$/d' | sed '/^#/d' | wc -l)
-  logInfo "TestCase: $(basename "$test_case_positive")"
-  echo "$test_results"
-  if test "$matched_elements" -lt "$given_elements"; then
-    logError "Test failed, to few elements found: $matched_elements/$given_elements"
-    exit 1
-  elif test "$matched_elements" -gt "$given_elements"; then
-    logError "Test failed, to many elements found: $matched_elements/$given_elements"
-    exit 1
-  else
-    logInfo "Test OK: $matched_elements/$given_elements"
-  fi
+  test_name_positive=${pattern_name//pattern/positive}
+  find "$test_path" -type f -name "$test_name_positive*.list" | sort | { while read -r test_case_positive;
+    do
+      test_results=$(getResults "$pattern_case" "$test_case_positive")
+      matched_elements=$(echo "$test_results" | sed '/^$/d' | wc -l)
+      given_elements=$(sed '/^pattern=/d' "$test_case_positive" | sed '/^$/d' | sed '/^#/d' | wc -l)
+      logInfo "TestCase: $(basename "$test_case_positive")"
+      echo "$test_results"
+      if test "$matched_elements" -lt "$given_elements"; then
+        logError "Test failed, to few elements found: $matched_elements/$given_elements"
+        exit 1
+      elif test "$matched_elements" -gt "$given_elements"; then
+        logError "Test failed, to many elements found: $matched_elements/$given_elements"
+        exit 1
+      else
+        logInfo "Test OK: $matched_elements/$given_elements"
+      fi
+  done }
+
   
   # negative tests
-  test_name_negative=${pattern_name//pattern/negative.list}
-  test_case_negative="$test_path/$test_name_negative"
-  test_results=$(getResults "$pattern_case" "$test_case_negative")
-  matched_elements=$(echo "$test_results" | sed '/^$/d' | wc -l)
-  given_elements=$(sed '/^pattern=/d' "$test_case_negative"| sed '/^$/d' | sed '/^#/d' | wc -l)
-  logInfo "TestCase: $(basename "$test_case_negative")"
-  if test "$matched_elements" -eq "0"; then
-    logInfo "Test OK: $matched_elements/$given_elements"
-  else
-    logError "Test failed, to many elements found: $matched_elements/$given_elements"
-    exit 1
-  fi
+  test_name_negative=${pattern_name//pattern/negative}
+  find "$test_path" -type f -name "$test_name_negative*.list" | sort | { while read -r test_case_negative;
+    do
+      test_results=$(getResults "$pattern_case" "$test_case_negative")
+      matched_elements=$(echo "$test_results" | sed '/^$/d' | wc -l)
+      given_elements=$(sed '/^pattern=/d' "$test_case_negative"| sed '/^$/d' | sed '/^#/d' | wc -l)
+      logInfo "TestCase: $(basename "$test_case_negative")"
+      if test "$matched_elements" -eq "0"; then
+        logInfo "Test OK: $matched_elements/$given_elements"
+      else
+        logError "Test failed, to many elements found: $matched_elements/$given_elements"
+        exit 1
+      fi
+  done }
 }
 
 function runSearch () {
