Tests verbessert

diff --git a/create_railroad_keywords_from_pdf b/create_railroad_keywords_from_pdf
--- a/create_railroad_keywords_from_pdf
+++ b/create_railroad_keywords_from_pdf
@@ -130,24 +130,27 @@ function runTest () {
   # positive tests
   test_name_positive=${pattern_name//pattern/positive}
   logInfo "$test_name_positive"
+  
   find "$test_path" -type f -name "$test_name_positive*.list" | sort | { while read -r test_case_positive;
     do
       test_results=$(getResults "$pattern_case" "$test_case_positive" "1")
-      matched_elements=$(echo "$test_results" | sed '/^[[:space:]]*$/d' | wc -l)
-      given_elements=$(sed '/^[[:space:]]*$/d' "$test_case_positive" | sed '/^[[:space:]]*#/d' | wc -l)
+      # matched_elements=$(echo "$test_results" | sed '/^[[:space:]]*$/d' | wc -l)
+      # given_elements=$(sed '/^[[:space:]]*$/d' "$test_case_positive" | sed '/^[[:space:]]*#/d' | wc -l)
       logInfo "TestCase: $(basename "$test_case_positive")"
       category=$(look category "$pattern_case" | cut -d '=' -f 2-)
-      echo "${test_results//$category./}"
-      if test "$matched_elements" -lt "$given_elements"; then
-        logError "Test failed, to few elements found: $matched_elements/$given_elements"
-        exit 1
-      elif test "$matched_elements" -gt "$given_elements"; then
-        logError "Test failed, to many elements found: $matched_elements/$given_elements"
-        exit 1
-      else
-        logInfo "Test OK: $matched_elements/$given_elements"
-      fi
+      test_results="${test_results//$category./}"
+      
+      temp_file_1="$script_path/test_results/$(basename "$test_case_positive").1"
+      temp_file_2="$script_path/test_results/$(basename "$test_case_positive").2"
+      
+      echo "$test_results" > "$temp_file_1"
+      echo "$test_results"
+      
+      sed '/^[[:space:]]*$/d' "$test_case_positive" | sed '/^[[:space:]]*#/d' | sed 's/^[[:space:]]*//g' | sed 's/[[:space:]]*$//g' > "$temp_file_2"
+      
+      diff -arq "$temp_file_1" "$temp_file_2"  >/dev/null 2>&1; if [ $? -gt 0 ]; then logError "Test failed."; exit 1; else logInfo "Test OK"; fi
   done }
+  
   if [ $? -gt 0 ]; then exit 1; fi
 
   logInfo "-----"
@@ -232,9 +235,14 @@ if [ ! -d "$pattern_path" ] && [ ! -d "$(dirname "$pattern_path")" ]; then
 fi
 
 if [ "$1" == "test" ]; then
+  
   "$script_path/tools/compress_pattern" "$2"
   "$script_path/tools/create_diffs" "$2"
-
+  
+  if [[ ! -f $2 ]]; then
+    rm "$script_path/test_results/"*.list.[12]
+  fi
+  
   time_complete_a=$(($(date +%s%N)/1000000))
   if [ -f "$pattern_path" ]; then
     runTest "$pattern_path"
