Genauer definierbare Falsch-Positv-Listen

diff --git a/extract_and_write_keywords_into_calibre b/extract_and_write_keywords_into_calibre
--- a/extract_and_write_keywords_into_calibre
+++ b/extract_and_write_keywords_into_calibre
@@ -48,52 +48,55 @@ fi
 find "$search_root" -type f -name '*.pdf' | {
   while read -r pdf_path; do
     
-    keywords=$(keywords run ~/src/RailroadKeywords/pattern "$pdf_path")
-    # if [ ! -z "$keywords" ]; then
-      echo "$pdf_path"
-      keywords=${keywords//Baureihe/BR}
-      keywords=$(echo "$keywords" | sort | uniq | tr '\n' ',' | sed -e 's/^,//g' | sed -e 's/,$//g' | sed -e 's/,{2,}//')
-      # keywords=$(echo "$keywords" | sort | uniq | sed -e 's/\n/, /' | sed -e 's/, $//')
-      # echo "$keywords"
-      
-      # old_keywords=$(exiftool -S -Subject "$pdf_path" | grep "Subject" | awk '{sub(/[^ ]+ /, ""); print $0}')
-      
-      # if [ "$old_keywords" == "$keywords" ]; then
-      #   echo "Keine Aktualisierung der Schlüsselwörter nötig."
-      # else
-      #   ebook-meta "$pdf_path" --tags="$keywords"
-      #   # Refresh md5 after a pdf update
-      working_path=$(dirname "$pdf_path")
-      pdf_filename=$(basename "$pdf_path")
-      pdf_filename="${pdf_filename%.*}"
-      #   md5=$(md5sum "$pdf_path"  | gawk  -F ' ' '{print $1}')
-      #   echo "$md5" > "$working_path/$pdf_filename.md5"
-      metadata_path="$working_path/metadata.opf"
-      if [ ! -f "$metadata_path" ]; then
-        echo "$metadata_path not found" 1>&2
-      else
-        
+  working_path=$(dirname "$pdf_path")
 
+  metadata_path="$working_path/metadata.opf"
+  if [ ! -f "$metadata_path" ]; then
+    echo "$metadata_path not found" 1>&2
+  else
+    calibre_id=$(xpath -q -e "//package/metadata/dc:identifier[@id='calibre_id']/text()" "$metadata_path")
+    # SubShell
+    keywords=$(find "$script_path/pattern" -type f -name '*.pattern' | {
+      while read -r pattern_path; do
+        keywords=$(keywords run "$pattern_path" "$pdf_path")
+        false_positive_pattern_path="$script_path/false_positive/$(basename "$pattern_path")"
+        if [ -f "$false_positive_pattern_path" ]; then
+          false_positive_pattern=$(grep "^$calibre_id=" "$false_positive_pattern_path" | gawk  -F "$calibre_id=" '{print $2}')
+          false_positive_pattern=$(echo "$false_positive_pattern" | sed -e 's/(/\\(/g' | sed -e 's/)/\\)/g' | sed -e 's/{/\\{/g' | sed -e 's/}/\\}/g' | sed -e 's/|/\\|/g')
+          if [ ! -z "$false_positive_pattern" ]; then
+            keywords=$(echo "$keywords" | sed -e "s/$false_positive_pattern/,/g")
+          fi
+        fi
+        echo "$keywords"
+      done
+    })
+    
+    echo "$pdf_path"
+    keywords=${keywords//Baureihe/BR}
+    keywords=$(echo "$keywords" | sort | uniq | tr '\n' ',' | sed -e 's/^,//g' | sed -e 's/,$//g' | sed -e 's/,{2,}//')
+    # keywords=$(echo "$keywords" | sort | uniq | sed -e 's/\n/, /' | sed -e 's/, $//')
+    # echo "$keywords"
+    
+    # old_keywords=$(exiftool -S -Subject "$pdf_path" | grep "Subject" | awk '{sub(/[^ ]+ /, ""); print $0}')
+    
+    # if [ "$old_keywords" == "$keywords" ]; then
+    #   echo "Keine Aktualisierung der Schlüsselwörter nötig."
+    # else
+    #   ebook-meta "$pdf_path" --tags="$keywords"
+    #   # Refresh md5 after a pdf update
+    
+    # pdf_filename=$(basename "$pdf_path")
+    # pdf_filename="${pdf_filename%.*}"
+    #   md5=$(md5sum "$pdf_path"  | gawk  -F ' ' '{print $1}')
+    #   echo "$md5" > "$working_path/$pdf_filename.md5"
 
-        calibre_id=$(xpath -q -e "//package/metadata/dc:identifier[@id='calibre_id']/text()" "$metadata_path")
-        false_positive_pattern=$(grep "^$calibre_id=" "$script_path/false_positive/by_calibre_id.pattern" | gawk  -F "$calibre_id=" '{print $2}')
-        # echo "$calibre_id"
-        false_positive_pattern=$(echo "$false_positive_pattern" | sed -e 's/(/\\(/g' | sed -e 's/)/\\)/g' | sed -e 's/{/\\{/g' | sed -e 's/}/\\}/g' | sed -e 's/|/\\|/g')
-        
-        # echo "$false_positive_pattern"
-        
-        if [ ! -z "$false_positive_pattern" ]; then
-          keywords=$(echo "$keywords" | sed -e "s/$false_positive_pattern/,/g")
-        fi
-        old_keywords=$(calibredb show_metadata "$calibre_id"  | grep "Tags" | awk -F: '{print $2}' | sed -e 's/^ *//' | sed -e 's/ *$//' | sed -e 's/, /,/g' )
-        echo "Tags old: >$old_keywords<"
-        echo "Tags new: >$keywords<"
-        if [ "$old_keywords" != "$keywords" ]; then
-          calibredb set_metadata --field tags:"$keywords" "$calibre_id"
-        fi
-      fi
-      # fi
-    # fi
+    old_keywords=$(calibredb show_metadata "$calibre_id"  | grep "Tags" | awk -F: '{print $2}' | sed -e 's/^ *//' | sed -e 's/ *$//' | sed -e 's/, /,/g' )
+    echo "Tags old: >$old_keywords<"
+    echo "Tags new: >$keywords<"
+    if [ "$old_keywords" != "$keywords" ]; then
+      calibredb set_metadata --field tags:"$keywords" "$calibre_id"
+    fi
+  fi
   done
 }
 
